kind: ConfigMap
apiVersion: v1
metadata:
  name: trino-configs
data:
  jvm.config: |-
    -server
    -Xmx16G
    -XX:-UseBiasedLocking
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+ExitOnOutOfMemoryError
    -XX:+UseGCOverheadLimit
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:ReservedCodeCacheSize=512M
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
  config.properties.coordinator: |-
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    query.max-memory=200GB
    query.max-memory-per-node=8GB
    query.max-total-memory-per-node=10GB
    query.max-stage-count=200
    task.writer-count=4
    discovery-server.enabled=true
    discovery.uri=http://trino.trino.svc.cluster.local:8080
  config.properties.worker: |-
    coordinator=false
    http-server.http.port=8080
    query.max-memory=200GB
    query.max-memory-per-node=10GB
    query.max-total-memory-per-node=10GB
    query.max-stage-count=200
    task.writer-count=4
    discovery.uri=http://trino.trino.svc.cluster.local:8080
  node.properties: |-
    node.environment=test
    spiller-spill-path=/tmp
    max-spill-per-node=4TB
    query-max-spill-per-node=1TB
  hive.properties: |-
    connector.name=hive
    hive.metastore.uri=thrift://hive-metastore.hive-metastore.svc.cluster.local:9083
    hive.allow-drop-table=true
    hive.max-partitions-per-scan=1000000
    hive.azure.abfs-storage-account=edabdstorage
    hive.azure.abfs-access-key=4FU2Snhgntx15rw1rNByEDll37WkDBkdZAI25sTN3WLqa0PRrGr0k+yFvH0OY6tXlNxpUmEmqV6BVIQCw1P2Pw==
  iceberg.properties: |-
    connector.name=iceberg
    hive.metastore.uri=thrift://hive-metastore.hive-metastore.svc.cluster.local:9083
    hive.max-partitions-per-scan=1000000
    hive.azure.abfs-storage-account=edabdstorage
    hive.azure.abfs-access-key=4FU2Snhgntx15rw1rNByEDll37WkDBkdZAI25sTN3WLqa0PRrGr0k+yFvH0OY6tXlNxpUmEmqV6BVIQCw1P2Pw==
  mysql.properties: |-
    connector.name=mysql
    connection-url=jdbc:mysql://mariadb.hive-metastore.svc.cluster.local:3306
    connection-user=root
    connection-password=rootPassword123
