apiVersion: v1
kind: Pod
metadata:
  name: {{ include "trino.fullname" . }}-worker-cli
spec:
  containers:
  - name: {{ .Chart.Name }}
    image: "{{ .Values.image.registry }}/{{ .Values.image.imagename }}:{{ .Values.image.tag }}"
    command: ["tail", "-f", "/dev/null"]
    imagePullPolicy: {{ .Values.image.pullPolicy }}
  restartPolicy: Always
