apiVersion: v1
kind: Service
metadata:
  name: {{ include "trino.fullname" . }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: ui
  selector:
    app.kubernetes.io/component: {{ .Values.trino.coordinator }}
